sonar.projectKey=bondar-app
sonar.projectName=bondar-app
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/dist/**,.venv/**,frontend/.env,backend/.coverage

# Python
sonar.python.version=3.12

# JS/Vue coverage (opțional, dacă generezi lcov)
# sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
